plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Используем стабильную платформу JUnit 5/6
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation("net.datafaker:datafaker:2.5.4")
    implementation("com.github.lalyos:jfiglet:0.0.8")

}

// ВСЕ настройки тестов собираем строго в одном блоке
test {
    useJUnitPlatform() // Находит твои тесты
    jvmArgs '-Dfile.encoding=UTF-8' // Обеспечивает UTF-8 при работе теста
}

// Настройка для запуска обычных методов main через JavaExec
tasks.withType(JavaExec) {
    jvmArgs '-Dfile.encoding=UTF-8'
}

// Говорим компилятору читать и собирать файлы *.java строго в UTF-8
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
