plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Используем стабильную платформу JUnit 5/6
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.junit.platform:junit-platform-suite'
    implementation("net.datafaker:datafaker:2.5.4")
    implementation("com.github.lalyos:jfiglet:0.0.8")
    testImplementation "io.cucumber:cucumber-java:7.18.0"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:7.18.0"
    testImplementation("io.rest-assured:rest-assured:6.0.0")
    testImplementation("org.projectlombok:lombok:1.18.46")
    implementation ("com.fasterxml.jackson.core:jackson-databind:2.18.2")
    implementation("com.codeborne:selenide:7.18.0")

}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}